### ISSUE TITLE
bpftrace -l to list available uprobes, got objdump: inaccessible or not found

### ISSUE THREAD

**Issue by b-ripper** [michalgr/bpftrace_local_manifest#2]
Hello michalgr,

I built Android R (kernel version 4.19) image for my device included your manifest of bpftrace functionality.

I got the error when list available uprobes:
`bpftrace -l uprobe:/apex/com.android.runtime/lib64/bionic/libc.so:*                                             
`
`sh: objdump: inaccessible or not found`

`bpftrace -e 'uprobe:/apex/com.android.runtime/lib64/bionic/libc.so:*pthread* { printf("read a line\n"); }'`
`LLVM ERROR: out of memory`

Do you have any suggestion? very thanks!

**Comment by michalgr** [comment]
Hi there !

[It seems that bpftrace uses objdump when `bcc_elf_foreach_sym` is not available](https://github.com/iovisor/bpftrace/blob/5bb653cf6b28294e71147e44c0c2fc49292aa167/src/bpftrace.cpp#L1801). It should be enough to define `HAVE_BCC_ELF_FOREACH_SYM` to make the problem go away.

I saw the OOM you're seeing on R as well. This is the commit in bpftrace that fixed the issue: https://github.com/iovisor/bpftrace/commit/954049043568350af934275202d4414f0f800db7

Let me recommend [ExtendedAndroidTools](https://github.com/facebookexperimental/ExtendedAndroidTools). Build scripts in that repo have both problems (and more) fixed. That is the way of building bpftrace and bcc for Android I want to maintain and support in the future.

**Comment by b-ripper** [comment]
Thanks for your reply!
